all:
  hosts:
  children:
    windows:
      hosts:
      children:
        hyperv:
          hosts:
            Blackbird:
              ansible_host: 192.168.1.191
              nomad_init_hostname: nomad-client-1
              nomad_init_ip: 192.168.1.210
    linux:
      hosts:
      children:
        storage:
          hosts:
            nfs:
              ansible_host: 192.168.1.20
              pvs: /dev/sda,/dev/sdc
        nomad_clients:
          hosts:
            nomad-client-1:
              ansible_host: 192.168.1.210