---
- name: Check if internal dns is working
  ansible.builtin.command: bash -c "nslookup google.com 192.168.1.2 || nslookup google.com 192.168.1.3"
  ignore_errors: true
  register: dnslookup

- name: Setting external dns
  set_fact:
    ns_1: 1.1.1.1
    ns_2: 8.8.8.8
  when: dnslookup.rc != 0

- name: Setting internal dns
  set_fact:
    ns_1: 192.168.1.2
    ns_2: 192.168.1.3
  when: dnslookup.rc == 0

- name: Set DNS
  ansible.builtin.template:
    src: ./linux/resolv.j2
    dest: /etc/resolv.conf